# Generated by Django 4.2.1 on 2023-06-27 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_doctor_patient_id_payment_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='role',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
