# Generated by Django 4.2.1 on 2023-07-30 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_payment_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='doctor_patient_id',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
