# Generated by Django 4.2.1 on 2023-09-07 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_payment_doctor_patient_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foydalanuvchi',
            fields=[
                ('id', models.CharField(max_length=111, primary_key=True, serialize=False)),
                ('balance', models.FloatField()),
            ],
        ),
    ]
