# Generated by Django 4.2.1 on 2023-09-07 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_foydalanuvchi'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Foydalanuvchi',
        ),
    ]
