# Generated by Django 4.2.1 on 2023-09-07 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_delete_foydalanuvchi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apteka',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('nomi', models.CharField(max_length=255)),
                ('rasm', models.CharField(max_length=255)),
                ('manzil', models.CharField(max_length=255)),
                ('moljal', models.CharField(max_length=255)),
                ('tel', models.IntegerField()),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('ish_vaqti_cheksiz', models.CharField(max_length=20)),
                ('hudud_id', models.IntegerField()),
                ('bosh_cat_id', models.IntegerField(blank=True, null=True)),
                ('reyting', models.FloatField()),
                ('comment', models.IntegerField()),
                ('ish_vaqti', models.TimeField()),
                ('tugash_vaqt', models.TimeField()),
            ],
            options={
                'db_table': 'apteka',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BemorChek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bemor_id', models.CharField(max_length=255)),
                ('chek_rasm', models.CharField(max_length=255)),
                ('amount', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('sana', models.DateTimeField()),
            ],
            options={
                'db_table': 'bemor_chek',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BemorHamshiraBuyurtma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bemor_id', models.CharField(max_length=255)),
                ('shifokor_id', models.CharField(blank=True, max_length=255, null=True)),
                ('bolalar_yoshi_id', models.IntegerField()),
                ('ism', models.CharField(max_length=255)),
                ('fam', models.CharField(max_length=255)),
                ('muddati', models.IntegerField()),
                ('status', models.CharField(max_length=100)),
                ('operator_id', models.IntegerField(blank=True, null=True)),
                ('jinsi', models.CharField(max_length=100)),
                ('manzil', models.CharField(max_length=255)),
                ('mamlakat', models.CharField(max_length=255)),
                ('longitude', models.CharField(max_length=255)),
                ('latitude', models.CharField(max_length=255)),
                ('viloyat_id', models.IntegerField()),
                ('tuman_id', models.IntegerField()),
                ('tel', models.CharField(max_length=30)),
                ('buyurtma_sana', models.DateTimeField()),
                ('boshlanish_sana', models.DateTimeField()),
            ],
            options={
                'db_table': 'bemor_hamshira_buyurtma',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BemorHamshiraMuolajaFk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyurtma_id', models.IntegerField()),
                ('muolaja_id', models.IntegerField()),
                ('hamshira_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(max_length=255)),
                ('sana', models.DateTimeField()),
            ],
            options={
                'db_table': 'bemor_hamshira_muolaja_fk',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BemorHaqida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bemor_id', models.CharField(max_length=255)),
                ('kasallik_matni', models.CharField(max_length=255)),
                ('allergiya', models.CharField(max_length=255)),
                ('surunkali', models.CharField(max_length=255)),
                ('sana', models.DateField()),
            ],
            options={
                'db_table': 'bemor_haqida',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BolalarYoshi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'bolalar_yoshi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Calculator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('normal', models.IntegerField()),
                ('bemor_id', models.CharField(max_length=111)),
                ('sana', models.DateField()),
                ('used', models.IntegerField()),
            ],
            options={
                'db_table': 'calculator',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CatXizmatlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idd', models.CharField(max_length=255)),
                ('xizmat_cat_id', models.IntegerField()),
                ('bosh_cat_id', models.IntegerField()),
                ('qurilma', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'cat_xizmatlar',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ChatTugallangan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bemor_id', models.CharField(max_length=255)),
                ('shifokor_id', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'chat_tugallangan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClickTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('click_paydoc_id', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('action', models.IntegerField()),
                ('status', models.IntegerField()),
                ('created', models.IntegerField()),
                ('modified', models.IntegerField()),
                ('extra_data', models.IntegerField()),
                ('message', models.IntegerField()),
            ],
            options={
                'db_table': 'click_transaction',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClickuzTransaction',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('click_trans_id', models.CharField(max_length=255)),
                ('merchant_trans_id', models.CharField(max_length=255)),
                ('amount', models.CharField(max_length=255)),
                ('action', models.CharField(max_length=255)),
                ('sign_string', models.CharField(max_length=255)),
                ('sign_datetime', models.DateTimeField()),
                ('status', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'clickuz_transaction',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('izoh', models.CharField(max_length=255)),
                ('reyting', models.FloatField(blank=True, null=True)),
                ('bosh_cat_id', models.IntegerField()),
                ('reyting_bosh_cat', models.CharField(max_length=255)),
                ('foydalanuvchi_id', models.CharField(max_length=255)),
                ('sana', models.DateTimeField()),
            ],
            options={
                'db_table': 'comment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ConsultationNavbat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bemor_id', models.CharField(db_collation='utf8mb4_unicode_ci', max_length=111)),
                ('doctor_id', models.CharField(db_collation='utf8mb4_unicode_ci', max_length=111)),
                ('sana', models.DateTimeField()),
                ('status_yakunlash', models.CharField(db_collation='utf8mb4_unicode_ci', max_length=255)),
                ('oldin_koringan', models.CharField(db_collation='utf8mb4_unicode_ci', max_length=255)),
                ('izoh', models.CharField(db_collation='utf8mb4_unicode_ci', max_length=500)),
                ('aloqa', models.CharField(blank=True, db_collation='utf8mb4_unicode_ci', max_length=111, null=True)),
                ('reyting', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'consultation_navbat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dezinfeksiya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('izoh', models.CharField(max_length=255)),
                ('sana', models.DateTimeField()),
            ],
            options={
                'db_table': 'dezinfeksiya',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DezinfeksiyaBuyurtma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bemor_id', models.CharField(max_length=255)),
                ('ism', models.CharField(max_length=255)),
                ('fam', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=100)),
                ('operator_id', models.CharField(blank=True, max_length=255, null=True)),
                ('jinsi', models.CharField(max_length=50)),
                ('manzil', models.CharField(max_length=255)),
                ('mamlakat', models.CharField(max_length=255)),
                ('longitude', models.CharField(max_length=255)),
                ('latitude', models.CharField(max_length=255)),
                ('viloyat_id', models.IntegerField()),
                ('tuman_id', models.IntegerField()),
                ('tel', models.CharField(max_length=20)),
                ('sana', models.DateTimeField()),
                ('chaqiruv_vaqti', models.DateTimeField()),
            ],
            options={
                'db_table': 'dezinfeksiya_buyurtma',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DezinfeksiyaBuyurtmaFk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dezinfeksiya_id', models.IntegerField()),
                ('dezinfeksiya_buyurtma_id', models.IntegerField()),
                ('sana', models.DateTimeField()),
            ],
            options={
                'db_table': 'dezinfeksiya_buyurtma_fk',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Diagnostika',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('nomi', models.CharField(max_length=255)),
                ('manzili', models.CharField(max_length=255)),
                ('moljal', models.CharField(max_length=255)),
                ('izoh', models.CharField(max_length=255)),
                ('tel', models.IntegerField()),
                ('viloyat_id', models.IntegerField()),
                ('tuman_id', models.IntegerField()),
                ('longtude', models.FloatField()),
                ('latude', models.FloatField()),
                ('karta_raqami', models.BigIntegerField()),
                ('narx', models.IntegerField()),
                ('sana', models.DateTimeField()),
                ('reyting', models.FloatField()),
                ('comment', models.IntegerField()),
            ],
            options={
                'db_table': 'diagnostika',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DiagnostikaKategoriya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'diagnostika_kategoriya',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DiagnostikaKatService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kat_id', models.IntegerField()),
                ('service_name', models.CharField(max_length=255)),
                ('rasm', models.CharField(blank=True, max_length=255, null=True)),
                ('info', models.TextField()),
            ],
            options={
                'db_table': 'diagnostika_kat_service',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DiagnostikaNavbat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostika_id', models.CharField(max_length=111)),
                ('bemor_id', models.CharField(max_length=111)),
                ('sana', models.DateTimeField()),
                ('status', models.CharField(max_length=111)),
                ('status2', models.CharField(max_length=111)),
                ('ism', models.CharField(max_length=111)),
                ('fam', models.CharField(max_length=111)),
                ('jins', models.CharField(max_length=111)),
                ('yosh', models.IntegerField()),
                ('tel', models.CharField(max_length=111)),
                ('viloyat_id', models.IntegerField()),
                ('tuman_id', models.IntegerField()),
                ('manzil', models.CharField(max_length=111)),
                ('longtude', models.CharField(max_length=111)),
                ('latude', models.CharField(max_length=111)),
            ],
            options={
                'db_table': 'diagnostika_navbat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DiagnostikaNavbatService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navbat_id', models.IntegerField()),
                ('servis_id', models.IntegerField()),
                ('bemor_sana', models.DateField()),
                ('bemor_vaqt', models.TimeField()),
                ('diagostika_sana', models.DateField(blank=True, null=True)),
                ('diagostika_vaqt', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(max_length=255)),
                ('izoh', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'diagnostika_navbat_service',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DiagnostikaOnOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostika_id', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'diagnostika_on_off',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DiagnostikaService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostic_id', models.CharField(max_length=255)),
                ('kat_id', models.IntegerField()),
                ('kat_service_id', models.IntegerField()),
                ('sana', models.DateField()),
                ('status', models.CharField(max_length=111)),
                ('ishga_kelish_vaqti', models.TimeField()),
                ('ortacha_vaqt', models.TimeField()),
                ('ketish_vaqti', models.TimeField()),
                ('summa', models.IntegerField()),
                ('skidka_narx', models.IntegerField()),
                ('xona', models.CharField(max_length=111)),
                ('uyga_chaqiruv', models.CharField(max_length=255)),
                ('obed_vaqti', models.TimeField()),
                ('obed_tugash_vaqti', models.TimeField()),
                ('dam_olish_kuni', models.CharField(max_length=255)),
                ('masul', models.CharField(max_length=255)),
                ('izoh', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'diagnostika_service',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DoctorPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_id', models.CharField(max_length=255)),
                ('username_tel', models.CharField(max_length=255)),
                ('hash_password', models.CharField(max_length=255)),
                ('tizimda', models.IntegerField()),
                ('online', models.DateTimeField()),
                ('block', models.IntegerField()),
            ],
            options={
                'db_table': 'doctor_password',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DocUserToken',
            fields=[
                ('ip', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.CharField(max_length=255)),
                ('token', models.CharField(max_length=255)),
                ('text', models.CharField(max_length=50)),
                ('sana', models.DateField()),
                ('vaqt', models.TimeField()),
            ],
            options={
                'db_table': 'doc_user_token',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('ism', models.CharField(max_length=255)),
                ('yoshi', models.IntegerField()),
                ('gurux', models.CharField(max_length=255)),
                ('manzili', models.CharField(max_length=255)),
                ('moljal', models.CharField(max_length=255)),
                ('tel', models.IntegerField()),
                ('hudud_id', models.IntegerField()),
                ('bosh_cat_id', models.IntegerField()),
                ('narx', models.IntegerField()),
                ('sana', models.DateField()),
                ('longtude', models.FloatField()),
                ('latude', models.FloatField()),
                ('reyting', models.FloatField()),
                ('comment', models.IntegerField()),
            ],
            options={
                'db_table': 'donor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DonorOrgan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_id', models.CharField(max_length=255)),
                ('organ', models.CharField(max_length=255)),
                ('xizmat_id', models.IntegerField()),
            ],
            options={
                'db_table': 'donor_organ',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dorilar',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('nomi', models.CharField(max_length=255)),
                ('narx', models.IntegerField()),
                ('ishlab_chiqarish', models.CharField(max_length=255)),
                ('sana', models.DateTimeField()),
                ('apteka_id', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'dorilar',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Foydalanuvchi',
            fields=[
                ('id', models.CharField(max_length=111, primary_key=True, serialize=False)),
                ('ism', models.CharField(max_length=255)),
                ('tugilgan_sana', models.CharField(max_length=255)),
                ('jinsi', models.CharField(max_length=255)),
                ('manzil', models.CharField(max_length=255)),
                ('mamlakat', models.CharField(max_length=255)),
                ('viloyat_id', models.IntegerField()),
                ('tuman_id', models.IntegerField()),
                ('tel', models.BigIntegerField()),
                ('letter', models.CharField(max_length=50)),
                ('gmail', models.CharField(max_length=255)),
                ('karta_raqami', models.CharField(max_length=255)),
                ('balance', models.FloatField()),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('disabled', models.IntegerField()),
                ('tizimda', models.IntegerField()),
                ('online', models.DateTimeField()),
                ('block', models.IntegerField()),
            ],
            options={
                'db_table': 'foydalanuvchi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FoydalanuvchiRasm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=255)),
                ('filename', models.CharField(max_length=255)),
                ('filename_id', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'foydalanuvchi_rasm',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HamshiraMuolaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('sana', models.DateTimeField()),
            ],
            options={
                'db_table': 'hamshira_muolaja',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HamshiraMuolajalarFk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shifokor_id', models.CharField(max_length=255)),
                ('muolaja_id', models.IntegerField()),
            ],
            options={
                'db_table': 'hamshira_muolajalar_fk',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hudud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=255)),
                ('rasm', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'hudud',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HududTuman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=255)),
                ('viloyat_id', models.IntegerField()),
            ],
            options={
                'db_table': 'hudud_tuman',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm', models.CharField(max_length=255)),
                ('idd', models.CharField(max_length=255)),
                ('bosh_cat_id', models.IntegerField()),
            ],
            options={
                'db_table': 'images',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KasallikTurlari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matn', models.CharField(max_length=255)),
                ('rasm', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'kasallik_turlari',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LandingMalumot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=255)),
                ('tel', models.IntegerField()),
                ('categoriya', models.CharField(max_length=255)),
                ('sana', models.DateField()),
            ],
            options={
                'db_table': 'landing_malumot',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=255)),
                ('doctor_id', models.CharField(blank=True, max_length=255, null=True)),
                ('diagnostic_id', models.CharField(blank=True, max_length=255, null=True)),
                ('sana', models.DateField()),
                ('status', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'marks',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Maslaxatlar',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=255)),
                ('post', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'maslaxatlar',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MostSeen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foydalanuvchi_id', models.CharField(max_length=255)),
                ('most_seen_id', models.CharField(max_length=255)),
                ('bosh_cat_id', models.IntegerField()),
                ('soni', models.IntegerField()),
            ],
            options={
                'db_table': 'most_seen',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Muloqot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_doctor', models.IntegerField()),
                ('shifokor_id', models.CharField(max_length=255)),
                ('foydalanuvchi_id', models.CharField(max_length=255)),
                ('chat', models.CharField(max_length=255)),
                ('rasm', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('status', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'muloqot',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('sana', models.DateTimeField()),
                ('status', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'notification',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oferta', models.TextField()),
            ],
            options={
                'db_table': 'oferta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OperatorChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sms', models.CharField(max_length=255)),
                ('user_id', models.CharField(max_length=255)),
                ('user_doctor_status', models.CharField(max_length=50)),
                ('operator_id', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('sana', models.DateTimeField()),
            ],
            options={
                'db_table': 'operator_chat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Parxez',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('retsept_id', models.CharField(max_length=255)),
                ('nomi', models.CharField(max_length=255)),
                ('status', models.IntegerField()),
                ('sana', models.DateTimeField()),
            ],
            options={
                'db_table': 'parxez',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ParxezUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
                ('photo', models.CharField(max_length=255)),
                ('izoh', models.TextField()),
            ],
            options={
                'db_table': 'parxez_users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PaycomuzTransaction',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('field_id', models.CharField(db_column='_id', max_length=255)),
                ('request_id', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('state', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(max_length=55)),
                ('cancel_datetime', models.CharField(blank=True, max_length=255, null=True)),
                ('created_datetime', models.CharField(blank=True, max_length=255, null=True)),
                ('order_key', models.CharField(blank=True, max_length=255, null=True)),
                ('perform_datetime', models.CharField(blank=True, max_length=255, null=True)),
                ('reason', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'paycomuz_transaction',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentsPayment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('completed', models.IntegerField()),
                ('type', models.CharField(max_length=10)),
                ('doctor_patient_id', models.CharField(blank=True, max_length=9, null=True)),
                ('role', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'payments_payment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloger_name', models.CharField(db_collation='utf8mb4_unicode_ci', max_length=255)),
                ('bloger_username', models.CharField(db_collation='utf8mb4_unicode_ci', max_length=255)),
                ('bloger_odam_soni', models.CharField(max_length=255)),
                ('promo_code', models.CharField(db_collation='utf8mb4_unicode_ci', max_length=255)),
                ('boshlash_vaqti', models.DateField()),
                ('tugash_vaqti', models.DateField()),
                ('active', models.CharField(db_collation='utf8mb4_unicode_ci', max_length=255)),
            ],
            options={
                'db_table': 'promo_code',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PromoCodeBemor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo_code_id', models.IntegerField()),
                ('bemor_id', models.CharField(db_collation='utf8mb4_unicode_ci', max_length=255)),
            ],
            options={
                'db_table': 'promo_code_bemor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QueueForTheDoctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_id', models.CharField(max_length=255)),
                ('patient_id', models.CharField(max_length=255)),
                ('operator_id', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('status', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'queue_for_the_doctor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Retsept',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('nomi', models.CharField(max_length=255)),
                ('user_id', models.CharField(max_length=255)),
                ('doctor_id', models.CharField(max_length=255)),
                ('sana', models.DateTimeField()),
                ('times', models.CharField(max_length=255)),
                ('status', models.IntegerField()),
            ],
            options={
                'db_table': 'retsept',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RetseptDori',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('retsept_id', models.CharField(max_length=255)),
                ('dori_nomi', models.CharField(max_length=255)),
                ('kun', models.IntegerField()),
                ('maxal', models.IntegerField()),
                ('comment', models.CharField(max_length=255)),
                ('ichildi', models.IntegerField()),
                ('vaqt', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'retsept_dori',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RetseptLanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ismi', models.CharField(max_length=255)),
                ('tel', models.IntegerField()),
                ('retsept_nomi', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'retsept_landing',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShifokorCarta',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('idd', models.CharField(max_length=255)),
                ('uzcart', models.BigIntegerField()),
                ('bosh_cat_id', models.IntegerField()),
            ],
            options={
                'db_table': 'shifokor_carta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShifokorHaqida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'shifokor_haqida',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShifokorKasallikFk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shifokor_id', models.CharField(max_length=255)),
                ('kasallik_id', models.IntegerField()),
            ],
            options={
                'db_table': 'shifokor_kasallik_fk',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShifokorKonsultatsiya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shifokor_id', models.CharField(max_length=255)),
                ('k_soni', models.IntegerField()),
                ('sana', models.DateField()),
            ],
            options={
                'db_table': 'shifokor_konsultatsiya',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Shifokorlar',
            fields=[
                ('id', models.CharField(max_length=255)),
                ('bosh_cat_id', models.IntegerField()),
                ('ism', models.CharField(max_length=255)),
                ('familiya', models.CharField(max_length=255)),
                ('rasm', models.CharField(max_length=255)),
                ('ish_joyi', models.CharField(max_length=255)),
                ('murojat_vaqti_dan', models.TimeField()),
                ('murojat_vaqti_gacha', models.TimeField()),
                ('mamlakat', models.CharField(max_length=255)),
                ('hudud_id', models.IntegerField()),
                ('tuman_id', models.IntegerField()),
                ('ish_boshlagan_sana', models.DateField()),
                ('sana', models.DateField()),
                ('toifasi', models.CharField(max_length=255)),
                ('vrach_haqida', models.IntegerField()),
                ('bolalar_yoshi_id', models.IntegerField()),
                ('tel', models.CharField(max_length=255)),
                ('til', models.CharField(blank=True, max_length=255, null=True)),
                ('narx', models.IntegerField()),
                ('xamshira_limit', models.DateField()),
                ('status', models.CharField(max_length=255)),
                ('online', models.DateTimeField()),
                ('reyting', models.FloatField(blank=True, null=True)),
                ('comment', models.IntegerField(blank=True, null=True)),
                ('idd', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'shifokorlar',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShifokorOqiganJoyi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm', models.CharField(max_length=255)),
                ('idd', models.CharField(max_length=255)),
                ('izoh', models.CharField(max_length=255)),
                ('chiqish_yili', models.IntegerField()),
                ('bosh_cat_id', models.IntegerField()),
            ],
            options={
                'db_table': 'shifokor_oqigan_joyi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShifokorSavollar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shifokor_id', models.CharField(max_length=255)),
                ('savol', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'shifokor_savollar',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Shifoxona',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('nomi', models.CharField(max_length=255)),
                ('hudud_id', models.IntegerField()),
                ('manzili', models.CharField(max_length=255)),
                ('rasm', models.CharField(max_length=255)),
                ('karta_raqami', models.BigIntegerField()),
                ('tel_nomer', models.IntegerField()),
                ('xona_qiymati', models.IntegerField()),
                ('malumotlari', models.CharField(max_length=255)),
                ('long', models.FloatField()),
                ('lat', models.FloatField()),
                ('bosh_cat_id', models.IntegerField()),
                ('reyting', models.FloatField()),
                ('comment', models.IntegerField()),
            ],
            options={
                'db_table': 'shifoxona',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShifoxonaSixatgoxNavbat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idd', models.CharField(max_length=255)),
                ('sh_s_xizmat_id', models.IntegerField()),
                ('bemor_id', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('vaqt_belgilash', models.TimeField()),
                ('sana', models.DateField()),
            ],
            options={
                'db_table': 'shifoxona_sixatgox_navbat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShifoxonaSixatgoxXizmat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idd', models.CharField(max_length=255)),
                ('xizmat_id', models.IntegerField()),
                ('narx', models.CharField(max_length=255)),
                ('skidka_narx', models.FloatField()),
                ('bosh_cat_id', models.IntegerField()),
            ],
            options={
                'db_table': 'shifoxona_sixatgox_xizmat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sixatgoh',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('nomi', models.CharField(blank=True, max_length=255, null=True)),
                ('izoh', models.CharField(blank=True, max_length=255, null=True)),
                ('manzili', models.CharField(blank=True, max_length=255, null=True)),
                ('moljal', models.CharField(blank=True, max_length=255, null=True)),
                ('longtude', models.FloatField(blank=True, null=True)),
                ('latude', models.FloatField(blank=True, null=True)),
                ('narxi', models.IntegerField(blank=True, null=True)),
                ('bosh_cat_id', models.IntegerField(blank=True, null=True)),
                ('hudud_id', models.IntegerField(blank=True, null=True)),
                ('tel', models.IntegerField(blank=True, null=True)),
                ('reyting', models.FloatField()),
                ('comment', models.IntegerField()),
            ],
            options={
                'db_table': 'sixatgoh',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Skidka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostika_id', models.CharField(max_length=255)),
                ('skidka_narx', models.IntegerField()),
            ],
            options={
                'db_table': 'skidka',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SmsStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sms_count', models.IntegerField()),
                ('phone', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('gmail', models.CharField(max_length=255)),
                ('sana', models.DateTimeField()),
            ],
            options={
                'db_table': 'sms_status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sorov',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=255)),
                ('darajasi', models.IntegerField()),
            ],
            options={
                'db_table': 'sorov',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('large_category_id', models.IntegerField()),
                ('sub_cat_id', models.IntegerField()),
                ('product_id', models.IntegerField()),
                ('product_price', models.FloatField()),
                ('product_quantity', models.IntegerField()),
                ('currency_id', models.IntegerField()),
                ('branch_id', models.IntegerField()),
                ('supplier_id', models.IntegerField()),
                ('datetimes', models.DateTimeField()),
                ('status', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'supply',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TaklifHamshira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bemor_hamshira_buyurtma_id', models.IntegerField()),
                ('price', models.IntegerField()),
                ('hamshira_id', models.CharField(max_length=255)),
                ('bemor_id', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
                ('sana', models.DateTimeField()),
            ],
            options={
                'db_table': 'taklif_hamshira',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TaklifHamshiraService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taklif_hamshira_id', models.IntegerField()),
                ('muolaja_id', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'taklif_hamshira_service',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TaklifShikoyat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('izoh', models.TextField()),
                ('idd', models.CharField(max_length=255)),
                ('cat', models.CharField(max_length=255)),
                ('c_id', models.IntegerField()),
                ('sana', models.DateTimeField()),
            ],
            options={
                'db_table': 'taklif_shikoyat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'test',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TestWebsocket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matn', models.CharField(max_length=255)),
                ('viloyat_id', models.IntegerField()),
            ],
            options={
                'db_table': 'test_websocket',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TexnikJihoz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idd', models.CharField(max_length=255)),
                ('nomi', models.CharField(max_length=255)),
                ('narxi', models.IntegerField()),
                ('uzunligi', models.IntegerField()),
                ('izoh', models.CharField(max_length=255)),
                ('apteka_id', models.CharField(max_length=255)),
                ('cat_id', models.IntegerField()),
            ],
            options={
                'db_table': 'texnik_jihoz',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TezkorHolat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tezkor_holat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TezkorSorov',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shifokor_id', models.CharField(blank=True, max_length=255, null=True)),
                ('bemor_id', models.CharField(max_length=255)),
                ('holat_name', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=100)),
                ('call_status', models.CharField(max_length=100)),
                ('batafsil', models.CharField(blank=True, max_length=255, null=True)),
                ('manzil', models.CharField(max_length=255)),
                ('rasm', models.CharField(blank=True, max_length=255, null=True)),
                ('tel', models.CharField(max_length=20)),
                ('sana', models.DateTimeField()),
            ],
            options={
                'db_table': 'tezkor_sorov',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TezYordam',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=255)),
                ('post', models.TextField()),
                ('tez_yordam_id', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tez_yordam',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idd', models.CharField(max_length=255)),
                ('ism', models.CharField(max_length=111)),
                ('phone', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('hashed_password', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('token', models.CharField(max_length=255)),
                ('disabled', models.IntegerField()),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserAvatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'user_avatar',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Xizmatlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=255)),
                ('izoh', models.CharField(max_length=255)),
                ('rasm', models.CharField(max_length=255)),
                ('bosh_cat_id', models.IntegerField()),
            ],
            options={
                'db_table': 'xizmatlar',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Yangiliklar',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('content', models.CharField(blank=True, max_length=255, null=True)),
                ('post', models.CharField(blank=True, max_length=255, null=True)),
                ('rasm', models.CharField(blank=True, max_length=255, null=True)),
                ('video_url', models.CharField(blank=True, max_length=255, null=True)),
                ('sana', models.DateTimeField()),
                ('korildi_soni', models.IntegerField()),
            ],
            options={
                'db_table': 'yangiliklar',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='YangiliklarKorilmadi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yangilik_id', models.CharField(max_length=255)),
                ('user_id', models.CharField(max_length=255)),
                ('sana', models.DateTimeField()),
            ],
            options={
                'db_table': 'yangiliklar_korilmadi',
                'managed': False,
            },
        ),
    ]
