# Generated by Django 4.2.1 on 2023-09-08 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_delete_apteka_delete_authgroup_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=8)),
                ('balance', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('tranzaksiya_id', models.IntegerField()),
            ],
            options={
                'db_table': 'balance_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Foydalanuvchi',
            fields=[
                ('id', models.CharField(max_length=111, primary_key=True, serialize=False)),
                ('payment_id', models.CharField(max_length=8)),
                ('ism', models.CharField(max_length=255)),
                ('tugilgan_sana', models.CharField(max_length=255)),
                ('jinsi', models.CharField(max_length=255)),
                ('manzil', models.CharField(max_length=255)),
                ('mamlakat', models.CharField(max_length=255)),
                ('viloyat_id', models.IntegerField()),
                ('tuman_id', models.IntegerField()),
                ('tel', models.BigIntegerField()),
                ('letter', models.CharField(max_length=50)),
                ('gmail', models.CharField(max_length=255)),
                ('karta_raqami', models.CharField(max_length=255)),
                ('balance', models.FloatField()),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('disabled', models.IntegerField()),
                ('tizimda', models.IntegerField()),
                ('online', models.DateTimeField()),
                ('block', models.IntegerField()),
            ],
            options={
                'db_table': 'foydalanuvchi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Shifokorlar',
            fields=[
                ('id', models.CharField(max_length=255)),
                ('payment_id', models.CharField(max_length=8)),
                ('bosh_cat_id', models.IntegerField()),
                ('ism', models.CharField(max_length=255)),
                ('familiya', models.CharField(max_length=255)),
                ('rasm', models.CharField(max_length=255)),
                ('ish_joyi', models.CharField(max_length=255)),
                ('murojat_vaqti_dan', models.TimeField()),
                ('murojat_vaqti_gacha', models.TimeField()),
                ('mamlakat', models.CharField(max_length=255)),
                ('hudud_id', models.IntegerField()),
                ('tuman_id', models.IntegerField()),
                ('ish_boshlagan_sana', models.DateField()),
                ('sana', models.DateField()),
                ('toifasi', models.CharField(max_length=255)),
                ('vrach_haqida', models.IntegerField()),
                ('bolalar_yoshi_id', models.IntegerField()),
                ('tel', models.CharField(max_length=255)),
                ('til', models.CharField(blank=True, max_length=255, null=True)),
                ('narx', models.IntegerField()),
                ('xamshira_limit', models.DateField()),
                ('status', models.CharField(max_length=255)),
                ('online', models.DateTimeField()),
                ('reyting', models.FloatField(blank=True, null=True)),
                ('comment', models.IntegerField(blank=True, null=True)),
                ('idd', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'shifokorlar',
                'managed': False,
            },
        ),
    ]
